services:
  zookeeper:
    container_name: "zookeeper"
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "./zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    build: .
    container_name: "kafka"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    volumes:
      - ./kafka_data:/data
  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     DYNAMIC_CONFIG_ENABLED: 'true'
  #     KAFKA_CLUSTERS_0_NAME: "local-cluster"
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
  #     KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
  #     KAFKA_CLUSTERS_0_METRICS: "true"
  #   volumes:
  #     - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
  #   depends_on:
  #     - kafka
  #     - zookeeper
